# Generated by Django 3.1.3 on 2021-04-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogMain', '0005_auto_20210422_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(auto_created=True)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_creation_date', models.DateField(auto_now_add=True)),
                ('blog_category', models.CharField(max_length=20)),
                ('blog_tags', models.TextField()),
                ('blog_content', models.TextField()),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogMain.userinfo')),
            ],
        ),
    ]
