# Generated by Django 3.1.4 on 2021-04-28 06:58

import blogapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogMain', '0006_userinfo_commented'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('blog_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='blog_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=255)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_thumbnail', models.ImageField(default="{static 'img/blog_thumbnail_default.jpg'}", upload_to=blogapp.models.Blog_article.upload_thumbnail)),
                ('blog_creation_date', models.DateTimeField(auto_now_add=True)),
                ('blog_category', models.CharField(max_length=20)),
                ('blog_tags', models.TextField(default='')),
                ('num_of_comments', models.IntegerField(default=0)),
                ('blog_views', models.IntegerField(default=0)),
                ('blog_upvote', models.IntegerField(default=0)),
                ('blog_downvote', models.IntegerField(default=0)),
                ('blog_content', models.TextField()),
                ('blog_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogMain.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='article_votes_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogMain.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='article_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=300)),
                ('comment_creation_date', models.DateField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_article')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogMain.userinfo')),
            ],
        ),
    ]
