# Generated by Django 3.1.4 on 2021-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_tags',
            name='blog_id',
            field=models.CharField(max_length=255),
        ),
    ]
