# Generated by Django 3.1.4 on 2021-04-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0006_userinfo_commented'),
        ('blogapp', '0002_auto_20210428_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article_comments',
            new_name='Article_comment',
        ),
        migrations.RenameModel(
            old_name='article_tags',
            new_name='Article_tag',
        ),
    ]
