# Generated by Django 3.1.3 on 2021-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210423_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_article',
            name='blog_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
