# Generated by Django 3.1.3 on 2021-04-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0005_auto_20210422_2103'),
        ('blogapp', '0003_auto_20210423_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_article',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='article_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=300)),
                ('comment_creation_date', models.DateTimeField(auto_now_add=True)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_article')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogMain.userinfo')),
            ],
        ),
    ]
