# Generated by Django 3.1.4 on 2021-04-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20210428_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_article',
            name='users_downvote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog_article',
            name='users_upvote',
            field=models.TextField(default=''),
        ),
    ]
