# Generated by Django 3.1.3 on 2021-04-23 16:02

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210423_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_article',
            name='blog_downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_article',
            name='blog_thumbnail',
            field=models.ImageField(default='userImages/defaultShow.jpg', upload_to=blogapp.models.blog_article.upload_thumbnail),
        ),
        migrations.AddField(
            model_name='blog_article',
            name='blog_upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog_article',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
