# Generated by Django 3.1.3 on 2021-04-23 16:05

import blogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20210423_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_article',
            name='blog_thumbnail',
            field=models.ImageField(default='img/blog-2.jpg', upload_to=blogapp.models.blog_article.upload_thumbnail),
        ),
    ]
