# Generated by Django 3.1.3 on 2021-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20210424_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_comments',
            name='comment_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
