# Generated by Django 3.1.3 on 2021-04-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0005_auto_20210422_2103'),
        ('blogapp', '0010_auto_20210424_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_votes_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('dislike', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogMain.userinfo')),
            ],
        ),
    ]
