# Generated by Django 3.1.4 on 2021-04-19 06:07

import blogMain.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='verifyUser',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('verificationCode', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('typeOf', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to=blogMain.models.user_directory_path1)),
                ('addressPrimary', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('postal', models.CharField(default='', max_length=50)),
                ('about', models.TextField(default='')),
                ('blogsViewed', models.IntegerField(default=0)),
                ('blogsPublished', models.IntegerField(default=0)),
                ('visitedSite', models.IntegerField(default=0)),
                ('isFirstVisit', models.BooleanField(default=True)),
                ('newUser', models.BooleanField(default=True)),
                ('checkCode', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
