# Generated by Django 3.1.4 on 2021-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0002_auto_20210419_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='typeOf',
            field=models.CharField(default='', max_length=50),
        ),
    ]
