# Generated by Django 3.1.3 on 2021-04-22 15:33

import blogMain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0004_auto_20210419_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pic',
            field=models.ImageField(default='userImages/defaultShow.jpg', upload_to=blogMain.models.user_directory_path1),
        ),
    ]
