# Generated by Django 3.1.4 on 2021-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0005_auto_20210422_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='commented',
            field=models.IntegerField(default=0),
        ),
    ]
