# Generated by Django 3.1.4 on 2021-04-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogMain', '0007_userinfo_blogscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='isFirstVisit',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='blogsLiked',
            field=models.IntegerField(default=0),
        ),
    ]
